In [1]:
import numpy as np

In [4]:
np.version.version

'2.2.3'

Dataset: Iris 



https://www.kaggle.com/datasets/uciml/iris?resource=download&select=Iris.csv

In [5]:
import pandas as pd

In [7]:
pd.__version__

'2.2.3'

In [77]:
dataset = pd.read_csv('Iris.csv')

In [78]:
dataset.shape

(150, 6)

In [80]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [81]:
dataset = dataset.iloc[np.random.permutation(len(dataset))]

In [82]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
17    18            5.1           3.5            1.4           0.3   
138  139            6.0           3.0            4.8           1.8   
81    82            5.5           2.4            3.7           1.0   
79    80            5.7           2.6            3.5           1.0   
47    48            4.6           3.2            1.4           0.2   

             Species  
17       Iris-setosa  
138   Iris-virginica  
81   Iris-versicolor  
79   Iris-versicolor  
47       Iris-setosa

In [83]:
dataset.groupby('Species').size()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [84]:
feature_columns = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
X = dataset[feature_columns]
Y = dataset['Species']

In [85]:
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
17             5.1           3.5            1.4           0.3
138            6.0           3.0            4.8           1.8
81             5.5           2.4            3.7           1.0
79             5.7           2.6            3.5           1.0
47             4.6           3.2            1.4           0.2

In [86]:
Y.head()

17         Iris-setosa
138     Iris-virginica
81     Iris-versicolor
79     Iris-versicolor
47         Iris-setosa
Name: Species, dtype: object

In [87]:
encode = {"Iris-setosa" : 0, "Iris-versicolor" : 1, "Iris-virginica" : 2}

# ! is there a way to optimize encoding labels without scikit
Y = Y.apply(lambda x:encode[x])

Y.head()

17     0
138    2
81     1
79     1
47     0
Name: Species, dtype: int64

In [88]:
Y.value_counts()

Species
0    50
2    50
1    50
Name: count, dtype: int64

In [89]:
split_idx = int(0.8 * len(X))
X_train, X_test = X[:split_idx], X[split_idx:]
Y_train, Y_test = Y[:split_idx], Y[split_idx:]

In [92]:
print("X",X.shape)
print("X_train", X_train.shape)
print("X_test", X_test.shape)
print("Y", Y.shape)
print("Y_train", Y_train.shape)
print("Y_test", Y_test.shape)

X (150, 4)
X_train (120, 4)
X_test (30, 4)
Y (150,)
Y_train (120,)
Y_test (30,)


In [102]:
def distance(x, y):
    return np.sqrt(np.sum((x-y)**2))

In [129]:
from collections import Counter
class KNN:

    def __init__(self, k = 3):
        self.k = k 
    
    def fit(self, X, Y):
        self.X_train = X
        self.Y_train = Y
    
    def predict(self, X):
        predicted_labels = [self._predict(x) for x in X]
        return np.array(predicted_labels)
    
    def _predict(self, x):
        distances = [distance(x, x_train) for x_train in self.X_train]
        indices = np.argsort(distances)[:self.k] # sorts according to distances and returns its indices
        knn = [self.Y_train[idx] for idx in indices]
        counter = Counter(knn).most_common(1) # most common frequency ; return [(key,value),...]
        return counter[0][0]



In [123]:
print(X_test[:5].to_numpy())

[[5.7 3.8 1.7 0.3]
 [5.  3.2 1.2 0.2]
 [6.7 3.1 4.4 1.4]
 [6.2 3.4 5.4 2.3]
 [4.6 3.6 1.  0.2]]


In [127]:
clf = KNN(k=3)
clf.fit(X_train.values, Y_train.to_numpy())
predictons = clf.predict(X_test.to_numpy())

In [128]:
accuracy = np.sum(predictons == Y_test.to_numpy())/len(Y_test)
print("accuracy", accuracy)

accuracy 0.9666666666666667


In [125]:
clf = KNN(k=5)
clf.fit(X_train.values, Y_train.to_numpy())
predictons = clf.predict(X_test.to_numpy())

In [126]:
accuracy = np.sum(predictons == Y_test.to_numpy())/len(Y_test)
print("accuracy", accuracy)

accuracy 1.0
